Modulo,Conteudos,Objetivos,Estudado
1,"Introdução à programação e ao Python; instalação; ambiente de desenvolvimento","Entender o que é programação e configurar o ambiente",
2,"Variáveis, tipos de dados, operadores, entrada e saída","Manipular dados e executar operações básicas",
3,"Condicionais (if, elif, else) e laços (for, while)","Construir lógica de decisão e repetição",
4,"Listas, tuplas, conjuntos e dicionários","Organizar e manipular coleções de dados",
5,"Funções, parâmetros, retorno, módulos e pacotes","Reutilizar e estruturar o código",
6,"Leitura e escrita de arquivos (texto, CSV, JSON)","Trabalhar com armazenamento de dados",
7,"Exceções e tratamento de erros","Criar programas mais robustos",
8,"Classes, objetos, herança e polimorfismo","Aplicar programação orientada a objetos",
9,"Bibliotecas padrão e externas; ambientes virtuais","Ampliar recursos da linguagem",
10,"Projeto prático e boas práticas","Integrar os conhecimentos em uma aplicação",